armrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  link1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: link1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  link2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: link2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  link3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: link3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  link4_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: link4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  link5_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: link5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  plat_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: plat_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
