armrobot:
  arm_robot_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - link5_joint
      - plat_joint
      
    gains:
      link1_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      link2_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      link3_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      link4_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      link5_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      plat_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
